on:
  push:
    branch:
      - develop

name: Test and deploy on develop environment
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # Setup Gradle 7.6.1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6.1

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Show Build
        run: |
          echo ======================
          ls -la
          echo ======================
          cd build
          ls -la
          echo ======================
          cd libs
          ls -la
          echo ======================

      - name: Publish APK
        uses: actions/upload-artifact@v2
        with:
          name: my-app
          path: build/libs/*.apk
