on:
  push:
    branch:
      - develop

name: Test and deploy on develop environment
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Gradle
        uses: gradle/wrapper-action@v6
        with:
          gradle-version: '7.6.1'

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Publish APK
        uses: actions/upload-artifact@v2
        with:
          name: my-app
          path: build/libs/*.apk
