on:
  push:
    branch:
      - develop

name: Test and deploy on develop environment
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

#      # Setup Java 17
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: 17
#          distribution: temurin
#
#      # Setup Gradle 7.6.1
#      - name: Setup Gradle
#        uses: gradle/gradle-build-action@v2
#        with:
#          gradle-version: 7.6.1
#
#      - name: Build with Gradle
#        run: ./gradlew build --no-daemon
#
#      - name: Publish APK
#        uses: actions/upload-artifact@v2
#        with:
#          name: my-app
#          path: build/libs/*.jar

      - name: Set up Google Cloud
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: mspr-388509

      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v0.4.0
        with:
          project_id: mspr-388509
          credentials: ${{ secrets.GCP_SA_KEY }}
          version: develop
          promote: true
          stop_previous_version: true
          app_dir: ./app # Chemin vers votre répertoire d'application
